projectTitle = "Water Vision"
modId = "water_vision"
modVersion = "1.5.0+1.21.6"
group = "com.theendercore"
githubRepo = "theendercore/WaterVision"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "TheEnderCore" ]
majorMinecraftVersion = "1.21.4"
minecraftVersion = "1.21.4"
fabricLoaderVersion = "0.16.14"
fabricApiVersion = "0.119.2+1.21.4"
fabricLangKotlinVersion = "1.13.2+kotlin.2.1.20"
license = "MIT"
modules = [ ]
modDescription = "See Better Under da Water!"
# Modmenu badges, values can be: [ library, deprecated ]
badges = [ ]
disableKotlin = true

[mappings]
    # You have 7 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    # CUSTOM: Custom mapping jar. Uses mappings version as file location
    type = "MOJANG"
    version = "1.21.4"