kotlin.code.style=official

maven_group = com.theendercore
mod_version = 1.1.0
modid = water_vision
mod_name = Water Vision
description = See Better Under da Water!

# Modrinth and CurseForge Ids for this project
modrinth_id = CXryw0YT
curse_id = 890050

archives_base_name = WaterVision

org.gradle.jvmargs=-Xmx4000m