[versions]
    java = "25"
    kotlin = "2.3.0"
    fabric_loom = "1.16-SNAPSHOT"
    iridium = "4.0.0"
    # Dependencies
    minecraft = "26.1"
    fabric_loader = "0.19.2"
    fabric_api = "0.145.1+26.1"
    fzzy_config = "0.7.6+26.1"
    # Compatibility
    # Runtime
    modmenu = "18.0.0-alpha.8"

[libraries]
    # Dependencies
    minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
    fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
    fzzy-config = { module = "me.fzzyhmstrs:fzzy_config", version.ref = "fzzy_config" }
    # Compatibility
    # Runtime
    modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]
    kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
    fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric_loom" }
    iridium = { id = "org.teamvoided.iridium", version.ref = "iridium" }
    iridium-publish = { id = "iridium.project.publish-script", version.ref = "iridium" }
    iridium-upload = { id = "iridium.mod.upload-script", version.ref = "iridium" }

